import React, { useState, useRef, useEffect } from 'react';
import { FileText, Download, ChevronRight, Layers, Edit2, Check } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export default function AccountPlan({ plan }) {
    const planRef = useRef();

    const handleExportPDF = async () => {
        if (!plan) return;

        try {
            const element = planRef.current;
            const canvas = await html2canvas(element, { scale: 2 });
            const imgData = canvas.toDataURL('image/png');

            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save(`${plan.company_name}_Research_Report.pdf`);
        } catch (error) {
            console.error("PDF Export failed:", error);
        }
    };

    if (!plan) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-slate-500 gap-4">
                <Layers size={48} className="opacity-20" />
                <p className="text-sm uppercase tracking-widest">No Data Available</p>
                <p className="text-xs opacity-50 max-w-[200px] text-center">Initiate a research sequence to generate a strategic account plan.</p>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col bg-slate-950/50">
            <div className="p-6 border-b border-white/5 flex justify-between items-center bg-black/20">
                <div>
                    <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-3">
                        <FileText className="text-indigo-400" />
                        {plan.company_name}
                    </h2>
                    <p className="text-xs text-slate-400 mt-1 font-mono">STRATEGIC RESEARCH DOSSIER</p>
                </div>
                <button
                    onClick={handleExportPDF}
                    className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-sm font-medium transition-all shadow-lg shadow-indigo-500/20"
                >
                    <Download size={16} />
                    Export PDF
                </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-8" ref={planRef}>
                {plan.sections.map((section, idx) => (
                    <Section key={idx} section={section} />
                ))}

                <div className="pt-8 border-t border-white/5 text-center">
                    <p className="text-xs text-slate-600 font-mono">GENERATED BY AI RESEARCH ASSISTANT • CONFIDENTIAL</p>
                </div>
            </div>
        </div>
    );
}

function Section({ section }) {
    const [isEditing, setIsEditing] = useState(false);
    const [content, setContent] = useState(section.content);

    return (
        <div className="group">
            <div className="flex items-center gap-3 mb-4">
                <div className="w-1 h-6 bg-indigo-500 rounded-full" />
                <h3 className="text-lg font-semibold text-slate-200">{section.title}</h3>
                <button
                    onClick={() => setIsEditing(!isEditing)}
                    className="opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-white/10 rounded"
                >
                    {isEditing ? <Check size={14} className="text-emerald-400" /> : <Edit2 size={14} className="text-slate-400" />}
                </button>
            </div>

            {isEditing ? (
                <textarea
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    className="w-full h-64 bg-black/30 border border-white/10 rounded-lg p-4 text-slate-300 text-sm font-mono focus:outline-none focus:border-indigo-500/50"
                />
            ) : (
                <div className="prose prose-invert prose-sm max-w-none text-slate-400 leading-relaxed">
                    <div dangerouslySetInnerHTML={{ __html: content.replace(/\n/g, '<br/>') }} />
                </div>
            )}
        </div>
    );
}